name: Workflow2
on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: my-artifact
      - run: cat test.txt
